server:
  port: 9090
spring:
  application:
    name: eshop-gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # 注册中心的URL
      username: nacos
      password: printfzx1023.@
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719
    gateway:
      discovery:
        locator:
          enabled: true
feign:
  sentinel:
    enabled: true
